language: R
sudo: required

matrix:
  include:
  - r: oldrel
  - r: release
  - r: devel

notifications:
  email: false

addons:
  apt:
    packages:
      - openjdk-7-jdk
      - maven
      - r-base-dev

before_install:
  - sudo R CMD javareconf
  - make build-jar